misfit-inc/hotelmilosantabarbara.com

- wp-content/themes/ic/header.php
> Paolo bug fix

- wp-content/themes/ic/404.php
- wp-content/themes/ic/functions.php
- wp-content/themes/ic/header.php
- wp-content/themes/ic/index.php
- wp-content/themes/ic/library/featured.php
- wp-content/themes/ic/library/history-slider.php
- wp-content/themes/ic/page.php
- wp-content/themes/ic/page_gallery.php
- wp-content/themes/ic/page_guide.php
- wp-content/themes/ic/page_home.php
- wp-content/themes/ic/page_press.php
- wp-content/themes/ic/page_rooms.php
- wp-content/themes/ic/page_specials.php
- wp-content/themes/ic/page_tripadvisor.php
- wp-content/themes/ic/single-packages.php
- wp-content/themes/ic/single-rooms.php
- wp-content/themes/ic/single-specials.php
- wp-content/themes/ic/single.php
> Image alt tag

- wp-content/themes/ic/404.php
- wp-content/themes/ic/archive.php
- wp-content/themes/ic/category.php
- wp-content/themes/ic/css/custom.css
- wp-content/themes/ic/css/media.css
- wp-content/themes/ic/page.php
- wp-content/themes/ic/page_blog.php
- wp-content/themes/ic/page_gallery.php
- wp-content/themes/ic/page_guide.php
- wp-content/themes/ic/page_press.php
- wp-content/themes/ic/page_rooms.php
- wp-content/themes/ic/page_specials.php
- wp-content/themes/ic/page_tripadvisor.php
- wp-content/themes/ic/search.php
- wp-content/themes/ic/single-packages.php
- wp-content/themes/ic/single-rooms.php
- wp-content/themes/ic/single-specials.php
- wp-content/themes/ic/single.php
- wp-content/themes/ic/style.css
> One h1 tag per page

- wp-content/themes/ic/tribe-events/list/content.php
- wp-content/themes/ic/tribe-events/single-event.php
- wp-content/themes/ic/tribe-events/tribe-events.css
> h1 tag tribe events hotelmilo

- wp-content/themes/ic/css/custom.css
> Nico home page span fix

- wp-content/themes/ic/404.php
- wp-content/themes/ic/header.php
- wp-content/themes/ic/library/featured.php
- wp-content/themes/ic/page.php
- wp-content/themes/ic/page_gallery.php
- wp-content/themes/ic/page_guide.php
- wp-content/themes/ic/page_press.php
- wp-content/themes/ic/page_rooms.php
- wp-content/themes/ic/page_specials.php
- wp-content/themes/ic/page_tripadvisor.php
- wp-content/themes/ic/single-rooms.php
- wp-content/themes/ic/single-specials.php
- wp-content/themes/ic/single.php
Tracking events reserve buttons
> Tracking events reserve buttons

- wp-content/themes/ic/css/custom.css
Fix Special Page hover styling
> Nico Special Page Hover Fix

- wp-content/themes/ic/css/custom.css
> Nico remove why blue

- wp-content/themes/ic/index.php
- wp-content/themes/ic/style.css
> Aljem bug 6206 home blog event

- wp-content/themes/ic/page_gallery.php
change description to image title
> change description to image title

- wp-content/themes/ic/page_gallery.php
fix double title photo gallery
> fix double title photo gallery

- wp-content/themes/ic/js/scripts.js
> first day of the week Sunday

- wp-content/themes/ic/header.php
> remove pride banner

- wp-content/themes/ic/library/thumb.php
> timthumb config change

- wp-content/themes/ic/header.php
> Nico IC Sweepstakes

- wp-content/plugins/misfit-no-index.php
pagination events calendar rel prev next
> pagination events calendar rel prev next

- wp-content/themes/ic/tribe-events/day/content.php
- wp-content/themes/ic/tribe-events/month/content.php
> correct usage heading tags

- wp-content/plugins/events-calendar-pro/src/Tribe/Recurrence/Meta.php
error not deleting trash on event
> error not deleting trash on event

- wp-content/themes/ic/footer.php
- wp-content/themes/ic/header.php
- wp-content/themes/ic/options/options_panel.php
> local business schema

- wp-content/themes/ic/header.php
> install google optimize

- wp-content/plugins/misfit-no-index.php
event calendar noindex on day week and month
> event calendar noindex on day week and month

- wp-content/themes/ic/header.php
- wp-content/themes/ic/library/scripts.php
mobile booking widget open same window
> mobile booking widget open same window

- wp-content/themes/ic/page_rooms.php
limit text display in room description
> limit text display in room description

- wp-content/themes/ic/page.php
- wp-content/themes/ic/page_blog.php
- wp-content/themes/ic/page_gallery.php
- wp-content/themes/ic/page_guide.php
- wp-content/themes/ic/page_rooms.php
- wp-content/themes/ic/page_specials.php
- wp-content/themes/ic/single.php
> implement yoast breadcrumbs

- wp-content/themes/ic/css/custom.css
- wp-content/themes/ic/options/project-options.php
- wp-content/themes/ic/page.php
> full screen feature

- wp-content/plugins/contact-form-submissions/Admin.php
- wp-content/plugins/contact-form-submissions/Submissions.php
- wp-content/plugins/contact-form-submissions/contact-form-submissions.php
- wp-content/plugins/contact-form-submissions/css/admin.css
- wp-content/plugins/contact-form-submissions/languages/contact-form-submissions.pot
- wp-content/plugins/contact-form-submissions/readme.txt
> rfp submission not received

- wp-content/themes/ic/css/custom.css
- wp-content/themes/ic/header.php
- wp-content/themes/ic/library/scripts.php
> Feature GDPR

- wp-content/themes/ic/404.php
- wp-content/themes/ic/archive.php
- wp-content/themes/ic/category.php
- wp-content/themes/ic/footer.php
- wp-content/themes/ic/functions.php
- wp-content/themes/ic/index.php
- wp-content/themes/ic/options/options_panel.php
- wp-content/themes/ic/page.php
- wp-content/themes/ic/page_blog.php
- wp-content/themes/ic/page_gallery.php
- wp-content/themes/ic/page_guide.php
- wp-content/themes/ic/page_home.php
- wp-content/themes/ic/page_landing_template_without_map.php
- wp-content/themes/ic/page_press.php
- wp-content/themes/ic/page_rooms.php
- wp-content/themes/ic/page_specials.php
- wp-content/themes/ic/page_tripadvisor.php
- wp-content/themes/ic/single-packages.php
- wp-content/themes/ic/single-rooms.php
- wp-content/themes/ic/single-specials.php
- wp-content/themes/ic/single.php
> Nico bug fix 7151

- wp-content/themes/ic/css/custom.css
> fix bullets on rooms detail page

- wp-content/themes/ic/single-rooms.php
update burger menu room page mobile view
> update burger menu room page mobile view

- wp-content/plugins/scheduled-post-trigger/readme.txt
- wp-content/plugins/scheduled-post-trigger/scheduled-post-trigger.php
> Plugin Installl

- wp-content/themes/ic/css/custom.css
- wp-content/themes/ic/footer.php
> web form submission text

- wp-content/plugins/misfit-no-index.php
date archive not indexing correctly
> date archive not indexing correctly

- wp-content/themes/ic/functions.php
change auto generated excerpt limit to 156 max
> change auto generated excerpt limit to 156 max

- wp-content/themes/ic/footer.php
> menu logo clickable link

- wp-content/themes/ic/functions.php
remove draft from post object acf field
> remove draft from post object acf field

- wp-content/themes/ic/footer.php
update back slash to foward slash
> update back slash to foward slash

- wp-content/themes/ic/css/custom.css
- wp-content/themes/ic/css/media.css
- wp-content/themes/ic/functions.php
- wp-content/themes/ic/js/scripts.js
- wp-content/themes/ic/page-press.php
> New Press Page Template

- wp-content/themes/ic/single-specials.php
> update offer sidebar

- wp-content/themes/ic/index.php
- wp-content/themes/ic/library/super-map.php
- wp-content/themes/ic/page_guide.php
> fix on redirected button maps

- wp-content/themes/ic/page_guide.php
> update redirected button maps

- wp-content/themes/ic/library/scripts.php
> fix javascript error conflicting with plugins
